### PR TITLE
Added june/july entries of TMWN

### PR DESCRIPTION
**Pull request by beef331**

### CODE REVIEW

**Comment by narimiran** [comment]
@flyx Regarding installing `NimYAML`, in its readme it says one should do `nimble install yaml`, but for me that command installs https://github.com/nim-appkit/yaml !?

**Comment by metagn** [comment]
> for me that command installs https://github.com/nim-appkit/yaml

Maybe `nimble refresh`? Although this is pretty old: https://github.com/nim-lang/packages/pull/359

Also it has been 17 days now.

**Comment by flyx** [comment]
@narimiran Sorry I didn't see this mention, guess I clicked a wrong button by accident somewhere. Basically what @metagn said. I have never had a user complaining about this for years, therefore I would assume it is a problem with your setup, please check if refreshing fixes it.

**Comment by narimiran** [comment]
> please check if refreshing fixes it.

It doesn't.

```
$ nimble search yaml
yaml:
  url:         https://github.com/nim-appkit/yaml (git)
  tags:        library, serialization, parsing, yaml
  description: YAML parser
  license:     MIT
  website:     https://github.com/nim-appkit/yaml
 
nimyaml:
  Alias for yaml
 
nyml:
  url:         https://github.com/openpeep/nyml (git)
  tags:        yaml, yaml-parser, yml, nyml
  description: Stupid simple YAML-like implementation from YAML to JsonNode
  license:     MIT
  website:     https://github.com/openpeep/nyml
```

**Comment by narimiran** [comment]
> deleting all local Nimble data and re-downloading it

This helped.


Now, back to the original topic:
Since a long time has passed, and these posts are usually published on the 1st of a month, I'll be publishing this on September 1st.

**Comment by beef331** [comment]
@narimiran can I get you to add the August entries as well when you go to publish this?

**Comment by narimiran** [comment]
> @narimiran can I get you to add the August entries as well when you go to publish this?

Fine by me, just push another commit here.

(Or we could keep that for August+September TMWN, which would be published in a month?)

**Pull request merged**
