### PR TITLE
This month with nim nov dec 22

### PR DESCRIPTION
**Pull request by pietroppeter**
taking over from @beef331 for this month to submit this month with nim (he gave ok on discord).

this month is actually tricky, as assets there is a gif  and a video, which are a bit big (around 12MB, 3MB). Nothing fancy, still way in the limit of github files but maybe instead of adding them as assets (as we did in the past) I could link them elsewhere (I was thinking of linking them to the github user content).

### CODE REVIEW

**Comment by pietroppeter** [comment]
Ho, any feedback on this?

**Comment by narimiran** [comment]
> Hi, any feedback on this?

I'll take a closer look at this either tonight or tomorrow.

> as assets there is a gif and a video, which are a bit big (around 12MB, 3MB). Nothing fancy, still way in the limit of github files but maybe instead of adding them as assets (as we did in the past) I could link them elsewhere (I was thinking of linking them to the github user content).

Yeah, hosting them elsewhere might be a better option.

**Comment by pietroppeter** [comment]
ok, done. I have left the small png asset hosted here, the others should link from githubusercontent

**Comment by narimiran** [comment]
I've pushed some corrections (don't forget to pull before pushing new stuff).

> Great learning material has been published: [the coding train], [the nature of code].

Are the links missing here?

**Comment by pietroppeter** [comment]
Thanks! yes, you are right they were missing (also [openprocessing]). Now fixed.

**Pull request merged**
