### PR TITLE
split documentation to 2 parts

### PR DESCRIPTION
**Pull request by bung87**
adjust navigation

for beginner:
they see features -> learn a bit of nim -> install it try play with 

for non-beginner:

click Documentation , check manual and document references directly.

it's a bit weird feeling, click "Documentation" and see "Getting started with Nim" for me.

refs: https://github.com/nim-lang/website/issues/318 likely fit this 

maybe add more commit to cover #242 in this PR as well. after investigation it's not a stable choice for putting it into main navigation. but put "Nimble Package Manager" and "Nimble Package Directory" sections together seems to be a improvement to me.

change "Documentation" to "Docs" and "Download" to "Install" make the navigation shorter, might not feel hesitant for adding extro "Packages" link.

and another thing I noticed is "Community" seems to be a stable choice putting into main navigation on language offical sites.

### CODE REVIEW

**Comment by ringabout** [comment]
See also https://github.com/nim-lang/website/pull/276

**Comment by bung87** [comment]
> See also #276

It's really bad idea to me, I don't find reason scroll down full screen to find the "Documentation" links

**Comment by ringabout** [comment]
cc @narimiran

**Comment by narimiran** [comment]
It was unified on purpose. 

"I have to scroll" is not a real problem, sorry.

**Comment by bung87** [comment]
that's two click + one scroll.

**Comment by rockcavera** [comment]
I also didn't like it when everything was unified under the Documentation link. The official documentation is lost among several other links (several that go outside of Nim itself).

I preferred the previous approach, where we had Learn and Documentation.

**Comment by bung87** [comment]
“[see my indignation when the unification happened](https://github.com/nim-lang/website/commit/260adcf72fd27f0948bd16e9a6a1cb241620e2cf)” , oh , as a experienced web developer, I'll convincing the ui designer or product manger change the idea. or atleast this won't be done by my hand.

**Comment by ZoomRmc** [comment]
Clearly, the manual, being the best specs we have, should be treated differently as the main source of truth (besides the actual code).

**Pull request closed without merging**
