### PR TITLE
Replace images

### PR DESCRIPTION
**Pull request by malyutinegor**
Fix of #58.

### CODE REVIEW

**Comment by Calinou** [comment]
Consider using [SVGO](https://github.com/svg/svgo) to optimize SVGs for smaller file sizes. You can use [SVGOMG](https://jakearchibald.github.io/svgomg/) to preview optimizations, to make sure to keep the vector's intended appearance.

**Comment by malyutinegor** [comment]
@Calinou, I optimized files at moment of commit, but thanks :D

**Comment by dom96** [comment]
@Calinou I'd rather keep originals of all SVGs for editing purposes. There is a build process for this website and any and all optimisations should be done then.

**Comment by dom96** [comment]
So now we have two nimble logo files :\

ugh, meh, I'll merge anyway.

**Comment by dom96** [comment]
Actually there are three... that's crossing the line. I'm going to delete nimble-old.

**Pull request merged**
