### PR TITLE
Some changes to the FAQ

### PR DESCRIPTION
**Pull request by Yardanico**
I also wanted to add a warning for using -d:danger in that it disables all runtime checks, what would be the best wording (e.g. something "-d:danger provides the best executables, but for most cases -d:release is better since it provides good performance with safety checks enabled")

For -d:lto and -d:strip see https://github.com/nim-lang/Nim/commit/d27bc03b21ea066134a297e61d0d18c901300ccc. There's a problem though - that commit will only be included in 1.4, so maybe we should both tell the old and new ways for LTO? 

P.S.: Please add "hacktoberfest" tag to the repo since we're participating in it :)

### CODE REVIEW

**Comment by Yardanico** [comment]
Removed Aporia because it's no longer in active development

**Comment by narimiran** [comment]
> P.S.: Please add "hacktoberfest" tag to the repo since we're participating in it :)

I thought I could do that (because I can merge PRs, etc.), but I can't. :/

> e.g. something "-d:danger provides the best executables, but for most cases -d:release is better since it provides good performance with safety checks enabled"

Yes, `-d:release` should definitely be mentioned in some way.

**Comment by Yardanico** [comment]
@narimiran I'm not good with making documents like this, so please check my phrasing of using -d:danger and -d:release :)

**Comment by Yardanico** [comment]
I also reordered the C compiler table so the most used compilers are at the top - just for convenience

**Comment by dom96** [comment]
> (my fork does though :P)

PR? :)

**Pull request merged**
