### PR TITLE
Don't affix navigation bar at the top of the screen on desktop.

### PR DESCRIPTION
**Pull request by dom96**
Nothing grinds my gears more than seeing the nav bar stickied to the top of my browser window. Hope you will agree with me here, this is already stickied on mobile and doesn't need to be stickied on desktop.

### CODE REVIEW

**Comment by Araq** [comment]
I don't agree at all! I like it this way much better. This way when you scroll down you don't immediately lose the nice navbar.

**Comment by Calinou** [comment]
I think this is a good idea. Fixed navigation bars were a big thing in 2016 when this website was designed, but they're not anymore :slightly_smiling_face: Vertical real estate is precious after all.

**Comment by Calinou** [comment]
Bump. Has any consensus been reached on this since this PR was opened?

**Comment by narimiran** [comment]
> Has a consensus been reached since this PR was opened?

> I like it this way much better. This way when you scroll down you don't immediately lose the nice navbar.

This is my opinion/rationale too. I'm closing this for now. If we change our minds in the future, we can reopen this and make this change.

**Pull request closed without merging**
