### PR TITLE
Added blog post to introduce This Month With Nim

### PR DESCRIPTION
**Pull request by beef331**
This seems like a proper way to announce this. Allowing me to maintain the submissions without being in the github team to give all of you a buffer of notifications for these PRs.

### CODE REVIEW

**Comment by dom96** [comment]
Since this is a guest post, you should add something like this https://github.com/nim-lang/website/blame/master/jekyll/_posts/2020-06-30-ray-tracing-in-nim.md#L7

**Comment by beef331** [comment]
Is there any reasong why this is being delayed?

**Comment by Araq** [comment]
No, there isn't. Ping @narimiran

**Comment by narimiran** [comment]
@beef331 I've made some slight changes to the post.

But before I merge/publish it, the instructions at https://github.com/beef331/website how to add one's content don't seem easy enough.
Can we make it easier for people to submit their content? E.g. just write in some issue about their project (no need to clone, pull, copy stuff around, modify it, send PR, etc.), and then we compile everything in a monthly post?

Yes, it will mean more work for us, but it will (probably) also mean more content submitted.

**Comment by beef331** [comment]
Well there we go hopefully that fits your desire.

**Pull request merged**
