### PR TITLE
Add pattern matching/fusion article

### PR DESCRIPTION
**Pull request by haxscramper**

### CODE REVIEW

**Comment by haxscramper** [comment]
This article is ready to be published, I'm just doing occasional fixups when something comes up.

**Comment by haxscramper** [comment]
Because changes in fusion were not conveyed in `1.4.4` post **at all** I added this to the article too (along with main pattern matchign description)

**Comment by narimiran** [comment]
> Because changes in fusion were not conveyed in 1.4.4 post at all

1.4.4 comes with the old version of `fusion`.

**Comment by haxscramper** [comment]
Fusion was ubundled from nim, and now is just a library, no? https://github.com/nim-lang/Nim/pull/16925

**Comment by narimiran** [comment]
Why closing it? I planned to publish it next week.

**Comment by haxscramper** [comment]
If I knew this I wouldn't close it. But I didn't and decided that I would be waiting before someone finally comes to conclusion about what fusion is, how it is shipped, what version, and so on.

**Comment by haxscramper** [comment]
I will reopen now

**Pull request closed without merging**
