### PR TITLE
move buttons to top

### PR DESCRIPTION
**Pull request by narimiran**
- replace "Learn Nim" button with a link to the playground
- specify the latest stable version of Nim

----

It has been reported that on smaller resolution screens the install button is not immediately seen, unlike other programming language websites, where it is always somewhere at the top, easily visible.

Screenshot:

screenshot

### CODE REVIEW

**Comment by alaviss** [comment]
Here are some of my other design concepts for the record :)

Screenshot_2020-05-11 Nim Programming Language

concept a

Screen Shot 2020-05-12 at 21 29 42

Inspirations where drawn from https://crystal-lang.org/, which on its own is a really beautiful website.

Though I think we might want some real designer touch on this :P

**Comment by alaviss** [comment]
Here's an another concept from @narimiran:

0BoVn6Z

**Comment by Calinou** [comment]
So far, I like the last one you posted the most.

**Comment by narimiran** [comment]
> So far, I like the last one you posted the most.

Me too :)

**Comment by alaviss** [comment]
My only dislike for that one is that the code blocks aren't aligned :p Probably fixable by adding one more block.

**Comment by alaviss** [comment]
@narimiran any update on this? We should get this out of the door before 1.4

And I think most agreed on your variant of the design so we should go with that instead :)

**Comment by narimiran** [comment]
I forgot about this :)

Yes, let's make it happen before 1.4

**Comment by narimiran** [comment]
Implemented the most liked variant. It is already live.

**Pull request closed without merging**
