### PR TITLE
I added a project

### PR DESCRIPTION
**Pull request by C-NERD**
so i just added a project i finished this month please check it if i did it correctly

### CODE REVIEW

**Comment by narimiran** [comment]
> please check it if i did it correctly

It doesn't seem correct.

It seems like you used https://github.com/nim-lang/website/pull/253/ as your template, but you haven't added anything. But that PR is superseded by https://github.com/nim-lang/website/pull/254 - you should pull that one, and add your stuff on top of it.

**Comment by C-NERD** [comment]
Ok

**Comment by C-NERD** [comment]
i need help. this pull request was made from a repo i forked from another repo which was forked from this repo. i am new to the whole contributing to open source thing so don't get mad at me but, i deleted the initial forked repo and i forked this repo again from the original source then i added my post to it. Is this enough to solve the problem ? Just asking before i make another pull request

**Comment by narimiran** [comment]
@beef331 can you help with this?

**Comment by beef331** [comment]
@C-NERD you want to make a fork and PR to [here](https://github.com/beef331/website) I'll be moderating the contributions to the monthly blog post then making a PR every month of all the contributed showcases.

**Comment by C-NERD** [comment]
@beef331  thanks I'll do that

**Pull request closed without merging**
