### PR TITLE
use_dark_highlighting in posts if has code block

### LINKED ISSUE #202: CSS Blog syntax highlight
CSS on the Blog for Syntax Highlight is too faded away, 
barely noticeable and wont help too much highlighting code from written text, 
maybe it can be improved by just using the same CSS as the landing page.
Minor bug.

## Blog 

blog-style

## Landing

landing-style

### PR DESCRIPTION
**Pull request by KingDarBoja**
Fixes #202

By the way, had to remove the `gemfile.lock` and the blog post with the `.adoc` extension to run it locally due to compilation errors.

### CODE REVIEW

**Comment by dom96** [comment]
Why not enable it for all posts?

**Comment by KingDarBoja** [comment]
> Why not enable it for all posts?

🤦‍♂️ I forgot the ones that dind't show up on my vscode search ` ```nim `. Give me a few minutes and I will do it.
By the way, should the `github.css` be preserved as the main idea should be using the `dracula` highlight theme for the entire website? Just saying.

**Comment by narimiran** [comment]
Can we make this work without the need to edit every single blogpost and adding `use_dark_highlighting: true`, i.e. can that be the default?

**Comment by KingDarBoja** [comment]
I will take a look this week, the default should be indeed dark and just pass an option to disable it to avoid using `use_dark_highlighting` on every file.

**Comment by dom96** [comment]
what does this look like? Screenshot?

**Pull request closed without merging**
