### PR TITLE
Reduce "Nim in Action" png size

### PR DESCRIPTION
**Pull request by tripleko**
I reduced the size of the nim_in_action_cover.png file to 386x485 using imagemagick (even though the homepage's img tag specified a height of 470, this was the actual max display I found when testing across multiple browsers). Then I ran it through OptiPNG for some more lossless file size savings.

The end result is ~52kb, much smaller than the current 1.6mb png.

I just replaced the file since the homepage is only place where the png was being used.

### CODE REVIEW

**Comment by davidlougheed** [comment]
It should be possible to reduce the size of this without affecting display on high DPI screens, which this PR would.

**Comment by noformnocontent** [comment]
@davidlougheed as if book cover is _that_ important thing about a programming language
sure, it could be re-drawn in vector and put as SVG, but let's get real &emdash; no one would look at that more than twice
the initial load-size/-speed of the webpage is way more important

**Comment by DrecDroid** [comment]
Why png if the image has no transparencies and It is not really needed to maintain the details, It is just a referential image. A jpeg with 70 quality meet the same requirements of the image.

**Comment by tripleko** [comment]
I see now that I misunderstood how things work. After looking at chrome dev tools, the height="470px" I was looking at is actually completely ignored because of the css rules for section#book img. I don't know what is the best solution, but I do think the original png file is way larger than necessary.

I resized the image to 445x559 and used OptiPNG to produce a 171kb file, which is still significantly smaller than the original. I'm not an expert, but I also think the size should be large enough now to not affect most (or any?) high DPI screens?

**Comment by noformnocontent** [comment]
@tripleko as @DrecDroid mentioned, double size of css-pixels (889x1118) as JPEG of ~70% quality is the way to go due to majority of the high-dpi screens being capped at 2.0 ratio

results in ~91kb file:

**Comment by tripleko** [comment]
@noformnocontent I see, thanks. I used the jpeg you provided.

**Comment by dom96** [comment]
Completely agree on keeping the resolution for high DPI screens. Thank you guys very much for the discussion and thank you @tripleko for the PR :)

**Comment by dom96** [comment]
Normally I try to avoid JPEGs but I think for this image it works well.

**Pull request merged**
