### PR TITLE
Add macro post

### PR DESCRIPTION
**Pull request by notTito**

### CODE REVIEW

**Comment by notTito** [comment]
@Araq can you comment on these changes to the macro, do they make any sense to you? Because I think I might delete this post and try something different instead.

**Comment by Araq** [comment]
> @Araq can you comment on these changes to the macro, do they make any sense to you? Because I think I might delete this post and try something different instead.

I only skimmed it, it seems fine though a bit boring. But hey, I've probably read/written too much introduction material into Nim's macros.

**Comment by notTito** [comment]
ok lol :)

**Comment by dom96** [comment]
Why closing?

**Comment by notTito** [comment]
I explained, think it doesn't worth it. If you want to merge it, then ok. But after my exams I might try again.

**Pull request closed without merging**
